import requests,time
import dryscrape

session = dryscrape.Session(base_url = 'http://sfbay.craigslist.org/')
session.visit('https://accounts.craigslist.org/login')
user_name = 'dahalbiplovechs@gmail.com'
password = 'uguru123'
input_info = session.at_xpath('//*[@id="inputEmailHandle"]')
input_info.set(user_name)
password_info = session.at_xpath('//*[@id="inputPassword"]')
password_info.set(password)
button = session.at_xpath('//*[@type="submit"]')
button.click()
time.sleep(2)
session.render('logging_in.png')
#FIRST_PAGE 
session.visit('https://post.craigslist.org/k/Vq_8dzJx5RG_GhombljUfQ/ZLobN?s=type')
time.sleep(2)
session.render('first_step.png')

#==============FIRST_PAGE_CATEGORIES==================#
job_offered = session.at_xpath('//*[@value="jo"]')
job_offered.click()
gig_offered = session.at_xpath('//*[@value="go"]')
#gig_offered.click()
resume_job_wanted = session.at_xpath('//*[@value="jw"]')
#resume_job_wanted.click()
housing_wanted = session.at_xpath('//*[@value="hw"]')
#housing_wanted.click()
housing_offered = session.at_xpath('//*[@value="fso"]')
#housing_offered.click()
for_sale_by_dealer = session.at_xpath('//*[@value="fsd"]')
wanted_by_owner = session.at_xpath('//*[@value="iwo"]')
#wanted_by_owner.click()
wanted_by_dealer = session.at_xpath('//*[@value="iwd"]')
#wanted_by_dealer.click()
service_offered = session.at_xpath('//*[@value="so"]')
#service_offered.click()
personal_and_romance = session.at_xpath('//*[@value="p"]')
#personal_and_romance.click()
community = session.at_xpath('//*[@value="checkbox"]')
community.click()
time.sleep(2)
session.render('second_step.png')

#------------JOB OFFERED============#
session.visit('https://post.craigslist.org/k/BnR1mjFx5RGTThombljUfQ/Ui9aY?s=cat')
accounting_finanace = session.at_xpath('//*[@value="23"]')
accounting_finanace.click()
admin_office = session.at_xpath('//*[@value="24"]')
admin_office.click()
architect = session.at_xpath('//*[@value="48"]')
architect.click()
art_media_designs = session.at_xpath('//*[@value="25"]')
art_media_designs.click()
business_mgmt = session.at_xpath('//*[@value="12"]')
business_mgmt.click()
customer_service = session.at_xpath('//*[@value="100"]')
customer_service.click()
education_teaching = session.at_xpath('//*[@value="75"]')
education_teaching.click()
et_cetera = session.at_xpath('//*[@value="15"]')
et_cetera.click()
food_beverage = session.at_xpath('//*[@value="129"]')
food_beverage.click()
goverment = session.at_xpath('//*[@value="61"]')
goverment.click()
health_care = session.at_xpath('//*[@value="26"]')
health_care.click()
human_resource = session.at_xpath('//*[@value="54"]')
human_resource.click()
internet_engineering = session.at_xpath('//*[@value="14"]')
internet_engineering.click()
legal_paralegal = session.at_xpath('//*[@valie="47"]')
legal_paralegal.click()
manufacturing = session.at_xpath('//*[@value="128"]')
manufacturing.click()
marketing = session.at_xpath('//*[@value="13"]')
marketing.click()
non_profit = session.at_xpath('//*[@value="28"]')
non_profit.click()
real_esate = session.at_xpath('//*[@value="127"]')
real_esate.click()
retail = session.at_xpath('//*[@value="27"]')
retail.click()
sales = session.at_xpath('//*[@value="49"]')
sales.click()
salon_spa_fitness = session.at_xpath('//*[@value="126"]')
salon_spa_fitness.click()
science_bio_tech = session.at_xpath('//*[@value="75"]')
science_bio_tech.click()
security = session.at_xpath('//*[@value="131"]')
security.click()
skilled_trades_artisan = session.at_xpath('//*[@value="59"]')
skilled_trades_artisan.click()
software_qa_db = session.at_xpath('//*[@value="21"]')
software_qa_db.click()
system_networking = session.at_xpath('//*[@value="50"]')
system_networking.click()
technical_support = session.at_xpath('//*[@value="55"]')
technical_support.click()
transportation = session.at_xpath('//*[@value="125"]')
transportation.click()
tv_film_video = session.at_xpath('//*[@value="52"]')
tv_film_video.click()
web_html_info_designs = session.at_xpath('//*[@value="11"]')
web_html_info_designs.click()
writing_editing = session.at_xpath('//*[@value="16"]')
writing_editing.click()

FIRST_FORM_SUBMISSION = session.at_xpath('//*[@type="submit"]')
FIRST_FORM_SUBMISSION.click()

#===== SECOND OPTIONS =====###
session.visit('https://post.craigslist.org/k/BnR1mjFx5RGTThombljUfQ/Ui9aY?s=gs')
hire_someone = session.at_xpath('//*[@value="G"]')
service_to_offer = session.at_xpath('//*[@value="S"]')
#====== THIRD OPTIONS ========####
session.visit('https://post.craigslist.org/k/BnR1mjFx5RGTThombljUfQ/Ui9aY?s=rtype')
seeking_employment = session.at_xpath('//*[@value="res"]')
offering_a_advertising_a_server = session.at_xpath('//*[@value="B"]')
offering_a_job = session.at_xpath('//*[@value="J"]')
offering_a_childcare = session.at_xpath('//*[@value="kid"]')
#========= FOURTH OPTIONS =======##
rooms_shares = session.at_xpath('//*[@value="18"]')
apt_housing_for_rent = session.at_xpath('//*[@value="1"]')
office_commerical = session.at_xpath('//*[@value="40"]')
parking_storage = session.at_xpath('//*[@value="41"]')
real_esate = session.at_xpath('//*[@value="144"]')
real_state_by_owner = session.at_xpath('//*[@value="143"]')
sublets_temporary = session.at_xpath('//*[@value="39"]')
vacation_rentals = session.at_xpath('//*[@value="99"]')

#========== FIFTH OPTION =========##
session.visit('https://post.craigslist.org/k/BnR1mjFx5RGTThombljUfQ/Ui9aY?s=hcat')
apts_wanted = session.at_xpath('//*[@value="2"]')
real_estate_wanted = session.at_xpath('//*[@value="121"]')
room_share_wanted = session.at_xpath('//*[@value="19"]')
sublet_temp_wanted = session.at_xpath('//*[@value="58"]')

##============ SIXTH OPTION ===============##
session.visit('https://post.craigslist.org/k/BnR1mjFx5RGTThombljUfQ/Ui9aY?s=cat')
antiques = session.at_xpath('//*[@value="150"]')
appliances = session.at_xpath('//*[@value="149"]')

#

# file_name = open('rss.xml')
# headers = {'content-type':'application/x-www-form-urlencoded'}
# # valdidation = requests.post('https://post.craigslist.org/bulk-rss/validate',headers=headers)
# post = requests.post('https://post.craigslist.org/bulk-rss/post',headers=headers,data=file_name)
# print post.text
