"""added password field to user table

Revision ID: 3d85314f49cc
Revises: 462a020ecbde
Create Date: 2014-01-22 18:54:05.705032

"""

# revision identifiers, used by Alembic.
revision = '3d85314f49cc'
down_revision = '462a020ecbde'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('user', sa.Column('password', sa.String(length=64), nullable=True))
    ### end Alembic commands ###
    pass


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    # op.drop_column('user', 'password')
    ### end Alembic commands ###
    pass
