"""first revision test

Revision ID: 3e7ef193043f
Revises: None
Create Date: 2014-01-22 11:03:07.863505

"""

# revision identifiers, used by Alembic.
revision = '3e7ef193043f'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    # op.create_table('user',
    # sa.Column('id', sa.Integer(), nullable=False),
    # sa.Column('name', sa.String(length=64), nullable=True),
    # sa.PrimaryKeyConstraint('id')
    # )
    ### end Alembic commands ###
    pass


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    # op.drop_table('user')
    ### end Alembic commands ###
    pass
