"""added email, name is not unique anymore

Revision ID: 462a020ecbde
Revises: 3e7ef193043f
Create Date: 2014-01-22 11:05:54.860264

"""

# revision identifiers, used by Alembic.
revision = '462a020ecbde'
down_revision = '3e7ef193043f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('user', sa.Column('email', sa.String(length=64), nullable=True))
    ### end Alembic commands ###
    pass


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    # op.drop_column('user', 'email')
    ### end Alembic commands ###
    pass
