"""test

Revision ID: 5253425dd1e0
Revises: None
Create Date: 2014-01-22 20:11:04.386964

"""

# revision identifiers, used by Alembic.
revision = '5253425dd1e0'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
