"""empty message

Revision ID: 11d4e8179a64
Revises: 2ae5ac781bd5
Create Date: 2015-11-16 21:17:35.618140

"""

# revision identifiers, used by Alembic.
revision = '11d4e8179a64'
down_revision = '2ae5ac781bd5'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('reset_password', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'reset_password')
    ### end Alembic commands ###
