"""empty message

Revision ID: 1205bb16d2c2
Revises: 34c38a39e44
Create Date: 2015-03-03 13:30:48.973317

"""

# revision identifiers, used by Alembic.
revision = '1205bb16d2c2'
down_revision = '34c38a39e44'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('university', sa.Column('school_logo_image_url', sa.String(), nullable=True))
    op.add_column('university', sa.Column('us_news_ranking', sa.Integer(), nullable=True))
    op.drop_column('university', 'school_logo')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('university', sa.Column('school_logo', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('university', 'us_news_ranking')
    op.drop_column('university', 'school_logo_image_url')
    ### end Alembic commands ###
