"""empty message

Revision ID: 12f90e9b151a
Revises: 4d8529477bb3
Create Date: 2015-03-11 11:17:48.792944

"""

# revision identifiers, used by Alembic.
revision = '12f90e9b151a'
down_revision = '4d8529477bb3'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
