"""empty message

Revision ID: 136273284895
Revises: 4101ccf4ac2b
Create Date: 2015-07-12 14:34:23.384579

"""

# revision identifiers, used by Alembic.
revision = '136273284895'
down_revision = '4101ccf4ac2b'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.Column('total_courses', sa.Integer(), nullable=True),
    sa.Column('total_universities', sa.Integer(), nullable=True),
    sa.Column('total_users', sa.Integer(), nullable=True),
    sa.Column('total_gurus', sa.Integer(), nullable=True),
    sa.Column('total_depts', sa.Integer(), nullable=True),
    sa.Column('total_popular_courses', sa.Integer(), nullable=True),
    sa.Column('gurus_24h', sa.Integer(), nullable=True),
    sa.Column('users_24h', sa.Integer(), nullable=True),
    sa.Column('visitors_24', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column(u'course', sa.Column('source_url', sa.String(), nullable=True))
    op.add_column(u'department', sa.Column('source_url', sa.String(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column(u'department', 'source_url')
    op.drop_column(u'course', 'source_url')
    op.drop_table('stats')
    ### end Alembic commands ###
