"""empty message

Revision ID: 13c026f49342
Revises: 15c451fb0e2
Create Date: 2015-11-30 02:40:48.470166

"""

# revision identifiers, used by Alembic.
revision = '13c026f49342'
down_revision = '15c451fb0e2'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('campaign', sa.Column('description', sa.String(), nullable=True))
    op.add_column('campaign', sa.Column('directory_based', sa.Boolean(), nullable=True))
    op.add_column('campaign', sa.Column('mandrill_tags', sa.String(), nullable=True))
    op.add_column('campaign', sa.Column('templated_args', sa.String(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('campaign', 'templated_args')
    op.drop_column('campaign', 'mandrill_tags')
    op.drop_column('campaign', 'directory_based')
    op.drop_column('campaign', 'description')
    ### end Alembic commands ###
