"""empty message

Revision ID: 1435916b4aa2
Revises: 356288871f17
Create Date: 2015-03-10 23:23:39.086579

"""

# revision identifiers, used by Alembic.
revision = '1435916b4aa2'
down_revision = '356288871f17'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('university', sa.Column('email_attributes', sa.String(), nullable=True))
    op.add_column('university', sa.Column('public_school_ranking', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('university', 'public_school_ranking')
    op.drop_column('university', 'email_attributes')
    ### end Alembic commands ###
