"""empty message

Revision ID: 152e9f582f0c
Revises: 3663cb2af20a
Create Date: 2016-02-21 16:03:37.189490

"""

# revision identifiers, used by Alembic.
revision = '152e9f582f0c'
down_revision = '3663cb2af20a'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('calendar_event', sa.Column('relationship_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'calendar_event', 'relationship', ['relationship_id'], ['id'])
    op.add_column('position', sa.Column('relationship_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'position', 'relationship', ['relationship_id'], ['id'])
    op.add_column('relationship', sa.Column('guru_calendar_id', sa.Integer(), nullable=True))
    op.add_column('relationship', sa.Column('student_calendar_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'relationship', 'calendar', ['guru_calendar_id'], ['id'])
    op.create_foreign_key(None, 'relationship', 'calendar', ['student_calendar_id'], ['id'])
    op.add_column('transaction', sa.Column('relationship_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'transaction', 'relationship', ['relationship_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transaction', type_='foreignkey')
    op.drop_column('transaction', 'relationship_id')
    op.drop_constraint(None, 'relationship', type_='foreignkey')
    op.drop_constraint(None, 'relationship', type_='foreignkey')
    op.drop_column('relationship', 'student_calendar_id')
    op.drop_column('relationship', 'guru_calendar_id')
    op.drop_constraint(None, 'position', type_='foreignkey')
    op.drop_column('position', 'relationship_id')
    op.drop_constraint(None, 'calendar_event', type_='foreignkey')
    op.drop_column('calendar_event', 'relationship_id')
    ### end Alembic commands ###
