"""empty message

Revision ID: 15c451fb0e2
Revises: 2461c74c2d1
Create Date: 2015-11-29 20:37:22.701742

"""

# revision identifiers, used by Alembic.
revision = '15c451fb0e2'
down_revision = '2461c74c2d1'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipient', sa.Column('campaign_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'recipient', 'campaign', ['campaign_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'recipient', type_='foreignkey')
    op.drop_column('recipient', 'campaign_id')
    ### end Alembic commands ###
