"""empty message

Revision ID: 197b8dd8caf1
Revises: 5278c6e6db9c
Create Date: 2015-02-16 12:57:26.177503

"""

# revision identifiers, used by Alembic.
revision = '197b8dd8caf1'
down_revision = '5278c6e6db9c'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('version', sa.Column('latest_android', sa.String(), nullable=True))
    op.add_column('version', sa.Column('latest_ios', sa.String(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('version', 'latest_ios')
    op.drop_column('version', 'latest_android')
    ### end Alembic commands ###
