"""empty message

Revision ID: 199584d9839f
Revises: e6a107bf6f6
Create Date: 2015-06-15 00:40:48.263049

"""

# revision identifiers, used by Alembic.
revision = '199584d9839f'
down_revision = 'e6a107bf6f6'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tag', sa.Column('admin_approved', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tag', 'admin_approved')
    ### end Alembic commands ###
