"""empty message

Revision ID: 1b2c3c83a2a0
Revises: 294d5bea7854
Create Date: 2015-12-10 16:15:45.582648

"""

# revision identifiers, used by Alembic.
revision = '1b2c3c83a2a0'
down_revision = '294d5bea7854'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resource', sa.Column('bg_hex_color', sa.String(), nullable=True))
    op.add_column('resource', sa.Column('font_hex_color', sa.String(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('resource', 'font_hex_color')
    op.drop_column('resource', 'bg_hex_color')
    ### end Alembic commands ###
