"""empty message

Revision ID: 1b3a71d91bdc
Revises: b6a9b1d89e5
Create Date: 2015-06-06 23:45:09.346846

"""

# revision identifiers, used by Alembic.
revision = '1b3a71d91bdc'
down_revision = 'b6a9b1d89e5'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('proposal', sa.Column('question_response', sa.String(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('proposal', 'question_response')
    ### end Alembic commands ###
