"""empty message

Revision ID: 1b8fd18b254c
Revises: 1f4753903cea
Create Date: 2015-03-12 16:35:36.963671

"""

# revision identifiers, used by Alembic.
revision = '1b8fd18b254c'
down_revision = '1f4753903cea'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('proposal', sa.Column('student_calendar_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'proposal', 'calendar', ['student_calendar_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'proposal', type_='foreignkey')
    op.drop_column('proposal', 'student_calendar_id')
    ### end Alembic commands ###
