"""empty message

Revision ID: 1bd0001087f7
Revises: 4867cbf98dce
Create Date: 2015-02-28 07:22:03.046310

"""

# revision identifiers, used by Alembic.
revision = '1bd0001087f7'
down_revision = '4867cbf98dce'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transaction', sa.Column('balance_after', sa.Float(), nullable=True))
    op.add_column('transaction', sa.Column('balance_before', sa.Float(), nullable=True))
    op.add_column('transaction', sa.Column('cashout_guru_id', sa.Integer(), nullable=True))
    op.add_column('transaction', sa.Column('charge_status', sa.String(), nullable=True))
    op.add_column('transaction', sa.Column('time_updated', sa.DateTime(), nullable=True))
    op.add_column('transaction', sa.Column('transfer_status', sa.String(), nullable=True))
    op.create_foreign_key(None, 'transaction', 'user', ['cashout_guru_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transaction', type_='foreignkey')
    op.drop_column('transaction', 'transfer_status')
    op.drop_column('transaction', 'time_updated')
    op.drop_column('transaction', 'charge_status')
    op.drop_column('transaction', 'cashout_guru_id')
    op.drop_column('transaction', 'balance_before')
    op.drop_column('transaction', 'balance_after')
    ### end Alembic commands ###
