"""empty message

Revision ID: 1bdb7d2eff90
Revises: 152e9f582f0c
Create Date: 2016-02-21 17:49:19.760074

"""

# revision identifiers, used by Alembic.
revision = '1bdb7d2eff90'
down_revision = '152e9f582f0c'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('request', sa.Column('relationship_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'request', 'relationship', ['relationship_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'request', type_='foreignkey')
    op.drop_column('request', 'relationship_id')
    ### end Alembic commands ###
