"""empty message

Revision ID: 1c5b3d184bf1
Revises: 1205bb16d2c2
Create Date: 2015-03-04 12:51:49.055567

"""

# revision identifiers, used by Alembic.
revision = '1c5b3d184bf1'
down_revision = '1205bb16d2c2'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('file', sa.Column('session_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'file', 'session', ['session_id'], ['id'])
    op.add_column('session', sa.Column('description', sa.String(), nullable=True))
    op.add_column('session', sa.Column('proposal_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'session', 'proposal', ['proposal_id'], ['id'])
    op.add_column('support', sa.Column('session_id', sa.Integer(), nullable=True))
    op.add_column('support', sa.Column('transaction_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'support', 'transaction', ['transaction_id'], ['id'])
    op.create_foreign_key(None, 'support', 'session', ['session_id'], ['id'])
    op.add_column('transaction', sa.Column('amount_refunded', sa.Float(), nullable=True))
    op.add_column('transaction', sa.Column('balance_transaction_id', sa.String(), nullable=True))
    op.add_column('transaction', sa.Column('refund_id', sa.String(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transaction', 'refund_id')
    op.drop_column('transaction', 'balance_transaction_id')
    op.drop_column('transaction', 'amount_refunded')
    op.drop_constraint(None, 'support', type_='foreignkey')
    op.drop_constraint(None, 'support', type_='foreignkey')
    op.drop_column('support', 'transaction_id')
    op.drop_column('support', 'session_id')
    op.drop_constraint(None, 'session', type_='foreignkey')
    op.drop_column('session', 'proposal_id')
    op.drop_column('session', 'description')
    op.drop_constraint(None, 'file', type_='foreignkey')
    op.drop_column('file', 'session_id')
    ### end Alembic commands ###
