"""empty message

Revision ID: 1ce3e6e07c4c
Revises: ea21455ab33
Create Date: 2015-02-09 19:14:36.988418

"""

# revision identifiers, used by Alembic.
revision = '1ce3e6e07c4c'
down_revision = 'ea21455ab33'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('request', 'description')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('request', sa.Column('description', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    ### end Alembic commands ###
