"""empty message

Revision ID: 1d605fb4d939
Revises: 136273284895
Create Date: 2015-07-25 12:39:53.626629

"""

# revision identifiers, used by Alembic.
revision = '1d605fb4d939'
down_revision = '136273284895'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('language',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('time_created', sa.DateTime(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('experience',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('time_created', sa.DateTime(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('years', sa.Integer(), nullable=True),
    sa.Column('admin_approved', sa.Boolean(), nullable=True),
    sa.Column('school_specific', sa.Boolean(), nullable=True),
    sa.Column('university_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['university_id'], ['university.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('guru-language_assoc',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('language_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['language_id'], ['language.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
    )
    op.add_column(u'user', sa.Column('email_friendly', sa.Boolean(), nullable=True))
    op.add_column(u'user', sa.Column('facetime_friendly', sa.Boolean(), nullable=True))
    op.add_column(u'user', sa.Column('guru_latest_time', sa.Integer(), nullable=True))
    op.add_column(u'user', sa.Column('hangouts_friendly', sa.Boolean(), nullable=True))
    op.add_column(u'user', sa.Column('messenger_friendly', sa.Boolean(), nullable=True))
    op.add_column(u'user', sa.Column('phone_friendly', sa.Boolean(), nullable=True))
    op.add_column(u'user', sa.Column('skype_friendly', sa.Boolean(), nullable=True))
    op.add_column(u'user', sa.Column('text_friendly', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column(u'user', 'text_friendly')
    op.drop_column(u'user', 'skype_friendly')
    op.drop_column(u'user', 'phone_friendly')
    op.drop_column(u'user', 'messenger_friendly')
    op.drop_column(u'user', 'hangouts_friendly')
    op.drop_column(u'user', 'guru_latest_time')
    op.drop_column(u'user', 'facetime_friendly')
    op.drop_column(u'user', 'email_friendly')
    op.drop_table('guru-language_assoc')
    op.drop_table('experience')
    op.drop_table('language')
    ### end Alembic commands ###
