"""empty message

Revision ID: 1da03ab458e1
Revises: 487e4d824be1
Create Date: 2015-12-09 01:08:34.514864

"""

# revision identifiers, used by Alembic.
revision = '1da03ab458e1'
down_revision = '487e4d824be1'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('portfolio_item', sa.Column('archived', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('portfolio_item', 'archived')
    ### end Alembic commands ###
