"""empty message

Revision ID: 1e2d5de564e4
Revises: a95db0310b0
Create Date: 2015-02-08 13:48:13.564648

"""

# revision identifiers, used by Alembic.
revision = '1e2d5de564e4'
down_revision = 'a95db0310b0'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('university', sa.Column('num_courses', sa.Integer(), nullable=True))
    op.add_column('university', sa.Column('num_emails', sa.Integer(), nullable=True))
    op.add_column('university', sa.Column('num_gurus', sa.Integer(), nullable=True))
    op.add_column('university', sa.Column('num_majors', sa.Integer(), nullable=True))
    op.add_column('university', sa.Column('num_students', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('university', 'num_students')
    op.drop_column('university', 'num_majors')
    op.drop_column('university', 'num_gurus')
    op.drop_column('university', 'num_emails')
    op.drop_column('university', 'num_courses')
    ### end Alembic commands ###
