"""empty message

Revision ID: 1e7cb67df458
Revises: 48ade5c27bcf
Create Date: 2015-02-16 17:15:32.962939

"""

# revision identifiers, used by Alembic.
revision = '1e7cb67df458'
down_revision = '48ade5c27bcf'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('build', sa.Column('time_created', sa.DateTime(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('build', 'time_created')
    ### end Alembic commands ###
