"""empty message

Revision ID: 1e9256b4a00b
Revises: 46be1e03f8d4
Create Date: 2015-10-05 15:22:38.855150

"""

# revision identifiers, used by Alembic.
revision = '1e9256b4a00b'
down_revision = '46be1e03f8d4'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('category', sa.Column('hex_color', sa.String(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('category', 'hex_color')
    ### end Alembic commands ###
