"""empty message

Revision ID: 1f4753903cea
Revises: 384d2b0b379a
Create Date: 2015-03-12 14:51:33.405510

"""

# revision identifiers, used by Alembic.
revision = '1f4753903cea'
down_revision = '384d2b0b379a'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('university', sa.Column('notes', sa.String(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('university', 'notes')
    ### end Alembic commands ###
