"""SAMIR: added pending_tutor_id, pending_tutor_description to Request table, adding is_active to Conversation

Revision ID: 2033e5f72a8c
Revises: 22e2186d4384
Create Date: 2014-12-03 21:30:13.482947

"""

# revision identifiers, used by Alembic.
revision = '2033e5f72a8c'
down_revision = '22e2186d4384'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversation', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.add_column('request', sa.Column('pending_tutor_description', sa.String(), nullable=True))
    op.add_column('request', sa.Column('pending_tutor_id', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('request', 'pending_tutor_id')
    op.drop_column('request', 'pending_tutor_description')
    op.drop_column('conversation', 'is_active')
    ### end Alembic commands ###
