"""empty message

Revision ID: 223d7ad7a26b
Revises: 689ec249aa7
Create Date: 2015-03-23 15:41:31.935581

"""

# revision identifiers, used by Alembic.
revision = '223d7ad7a26b'
down_revision = '689ec249aa7'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('email_user', sa.Column('call_to_action_clicked', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('email_user', 'call_to_action_clicked')
    ### end Alembic commands ###
