"""empty message

Revision ID: 22e2186d4384
Revises: 51cff19af108
Create Date: 2014-12-03 21:13:09.934883

"""

# revision identifiers, used by Alembic.
revision = '22e2186d4384'
down_revision = '51cff19af108'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
