"""empty message

Revision ID: 23d5dcafb47
Revises: 4e7f60fde00e
Create Date: 2015-11-27 13:42:38.180764

"""

# revision identifiers, used by Alembic.
revision = '23d5dcafb47'
down_revision = '4e7f60fde00e'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('portfolio_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('time_created', sa.DateTime(), nullable=True),
    sa.Column('is_custom', sa.Boolean(), nullable=True),
    sa.Column('admin_approved', sa.Boolean(), nullable=True),
    sa.Column('skill_id', sa.Integer(), nullable=True),
    sa.Column('course_id', sa.Integer(), nullable=True),
    sa.Column('subcategory_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('avg_rating', sa.Float(), nullable=True),
    sa.Column('hourly_price', sa.Float(), nullable=True),
    sa.Column('max_hourly_price', sa.Float(), nullable=True),
    sa.Column('unit_price', sa.Float(), nullable=True),
    sa.Column('max_unit_price', sa.Float(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], ),
    sa.ForeignKeyConstraint(['skill_id'], ['skill.id'], ),
    sa.ForeignKeyConstraint(['subcategory_id'], ['subcategory.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('experience-portfolio-items_assoc',
    sa.Column('portfolio_item_id', sa.Integer(), nullable=True),
    sa.Column('experience_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['experience_id'], ['experience.id'], ),
    sa.ForeignKeyConstraint(['portfolio_item_id'], ['portfolio_item.id'], )
    )
    op.add_column(u'calendar_event', sa.Column('_type', sa.String(), nullable=True))
    op.add_column(u'calendar_event', sa.Column('archived', sa.Boolean(), nullable=True))
    op.add_column(u'calendar_event', sa.Column('course_id', sa.Integer(), nullable=True))
    op.add_column(u'calendar_event', sa.Column('description', sa.String(), nullable=True))
    op.add_column(u'calendar_event', sa.Column('private', sa.Boolean(), nullable=True))
    op.add_column(u'calendar_event', sa.Column('title', sa.String(), nullable=True))
    op.create_foreign_key(None, 'calendar_event', 'course', ['course_id'], ['id'])
    op.add_column(u'rating', sa.Column('portfolio_item_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'rating', 'portfolio_item', ['portfolio_item_id'], ['id'])
    op.add_column(u'resource', sa.Column('description', sa.String(), nullable=True))
    op.add_column(u'resource', sa.Column('portfolio_item_id', sa.Integer(), nullable=True))
    op.add_column(u'resource', sa.Column('title', sa.String(), nullable=True))
    op.create_foreign_key(None, 'resource', 'portfolio_item', ['portfolio_item_id'], ['id'])
    op.add_column(u'user', sa.Column('guru_calendar_id', sa.Integer(), nullable=True))
    op.add_column(u'user', sa.Column('referral_limit', sa.Integer(), nullable=True))
    op.add_column(u'user', sa.Column('student_calendar_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'user', 'calendar', ['guru_calendar_id'], ['id'])
    op.create_foreign_key(None, 'user', 'calendar', ['student_calendar_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_column(u'user', 'student_calendar_id')
    op.drop_column(u'user', 'referral_limit')
    op.drop_column(u'user', 'guru_calendar_id')
    op.drop_constraint(None, 'resource', type_='foreignkey')
    op.drop_column(u'resource', 'title')
    op.drop_column(u'resource', 'portfolio_item_id')
    op.drop_column(u'resource', 'description')
    op.drop_constraint(None, 'rating', type_='foreignkey')
    op.drop_column(u'rating', 'portfolio_item_id')
    op.drop_constraint(None, 'calendar_event', type_='foreignkey')
    op.drop_column(u'calendar_event', 'title')
    op.drop_column(u'calendar_event', 'private')
    op.drop_column(u'calendar_event', 'description')
    op.drop_column(u'calendar_event', 'course_id')
    op.drop_column(u'calendar_event', 'archived')
    op.drop_column(u'calendar_event', '_type')
    op.drop_table('experience-portfolio-items_assoc')
    op.drop_table('portfolio_item')
    ### end Alembic commands ###
