"""empty message

Revision ID: 23f9b2704276
Revises: 1ce3e6e07c4c
Create Date: 2015-02-09 19:15:00.941374

"""

# revision identifiers, used by Alembic.
revision = '23f9b2704276'
down_revision = '1ce3e6e07c4c'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('request', sa.Column('description', sa.String(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('request', 'description')
    ### end Alembic commands ###
