"""empty message

Revision ID: 2461c74c2d1
Revises: 23d5dcafb47
Create Date: 2015-11-27 16:17:21.059224

"""

# revision identifiers, used by Alembic.
revision = '2461c74c2d1'
down_revision = '23d5dcafb47'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('first_degree_referrals', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('second_degree_referrals', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'second_degree_referrals')
    op.drop_column('user', 'first_degree_referrals')
    ### end Alembic commands ###
