"""empty message

Revision ID: 25ec6f74b7f1
Revises: 289c1dfb1a56
Create Date: 2015-11-26 20:06:29.107787

"""

# revision identifiers, used by Alembic.
revision = '25ec6f74b7f1'
down_revision = '289c1dfb1a56'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('university', sa.Column('banner_url_confirmed', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('university', 'banner_url_confirmed')
    ### end Alembic commands ###
