"""empty message

Revision ID: 26252dce4c85
Revises: 59075ca6c0ef
Create Date: 2015-01-27 11:47:35.884187

"""

# revision identifiers, used by Alembic.
revision = '26252dce4c85'
down_revision = '59075ca6c0ef'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('version', sa.Column('android_msg', sa.String(), nullable=True))
    op.add_column('version', sa.Column('ios_msg', sa.String(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('version', 'ios_msg')
    op.drop_column('version', 'android_msg')
    ### end Alembic commands ###
