"""empty message

Revision ID: 27f1fd7c92d
Revises: 59c982a7d8c9
Create Date: 2015-11-22 00:24:28.654888

"""

# revision identifiers, used by Alembic.
revision = '27f1fd7c92d'
down_revision = '59c982a7d8c9'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('card', sa.Column('bank_currency', sa.String(), nullable=True))
    op.add_column('card', sa.Column('bank_last4', sa.String(), nullable=True))
    op.add_column('card', sa.Column('bank_name', sa.String(), nullable=True))
    op.add_column('card', sa.Column('bank_routing_number', sa.String(), nullable=True))
    op.add_column('card', sa.Column('is_bank_account', sa.Boolean(), nullable=True))
    op.add_column('card', sa.Column('recipient_email', sa.String(), nullable=True))
    op.add_column('card', sa.Column('stripe_bank_id', sa.String(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('card', 'stripe_bank_id')
    op.drop_column('card', 'recipient_email')
    op.drop_column('card', 'is_bank_account')
    op.drop_column('card', 'bank_routing_number')
    op.drop_column('card', 'bank_name')
    op.drop_column('card', 'bank_last4')
    op.drop_column('card', 'bank_currency')
    ### end Alembic commands ###
