"""empty message

Revision ID: 289c1dfb1a56
Revises: 27f1fd7c92d
Create Date: 2015-11-22 19:32:26.942934

"""

# revision identifiers, used by Alembic.
revision = '289c1dfb1a56'
down_revision = '27f1fd7c92d'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transaction', sa.Column('description', sa.String(), nullable=True))
    op.add_column('transaction', sa.Column('refunded', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transaction', 'refunded')
    op.drop_column('transaction', 'description')
    ### end Alembic commands ###
