"""empty message

Revision ID: 28fcd465f4b3
Revises: 2e436311abbd
Create Date: 2015-08-09 19:43:57.525604

"""

# revision identifiers, used by Alembic.
revision = '28fcd465f4b3'
down_revision = '2e436311abbd'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('university', sa.Column('fa15_end', sa.DateTime(), nullable=True))
    op.add_column('university', sa.Column('fa15_start', sa.DateTime(), nullable=True))
    op.add_column('university', sa.Column('sp15_end', sa.DateTime(), nullable=True))
    op.add_column('university', sa.Column('sp15_start', sa.DateTime(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('university', 'sp15_start')
    op.drop_column('university', 'sp15_end')
    op.drop_column('university', 'fa15_start')
    op.drop_column('university', 'fa15_end')
    ### end Alembic commands ###
