"""empty message

Revision ID: 294d5bea7854
Revises: 1da03ab458e1
Create Date: 2015-12-10 07:07:50.446273

"""

# revision identifiers, used by Alembic.
revision = '294d5bea7854'
down_revision = '1da03ab458e1'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
