"""empty message

Revision ID: 295459b37a74
Revises: 21a2c7aba6ef
Create Date: 2014-11-28 17:42:56.078834

"""

# revision identifiers, used by Alembic.
revision = '295459b37a74'
down_revision = '21a2c7aba6ef'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('test_name', sa.String(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'test_name')
    ### end Alembic commands ###
