"""empty message

Revision ID: 2aa944bb9096
Revises: 3497ca226fe6
Create Date: 2015-10-10 12:16:30.594780

"""

# revision identifiers, used by Alembic.
revision = '2aa944bb9096'
down_revision = '3497ca226fe6'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('university', sa.Column('seal_url', sa.String(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('university', 'seal_url')
    ### end Alembic commands ###
