"""empty message

Revision ID: 2ae5ac781bd5
Revises: 2aa944bb9096
Create Date: 2015-10-10 12:53:45.273188

"""

# revision identifiers, used by Alembic.
revision = '2ae5ac781bd5'
down_revision = '2aa944bb9096'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('university', sa.Column('variations', sa.String(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('university', 'variations')
    ### end Alembic commands ###
