"""empty message

Revision ID: 2ce926c3cc69
Revises: d9e1564e623
Create Date: 2015-12-04 22:26:30.378647

"""

# revision identifiers, used by Alembic.
revision = '2ce926c3cc69'
down_revision = 'd9e1564e623'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('course', sa.Column('code', sa.String(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('course', 'code')
    ### end Alembic commands ###
