"""empty message

Revision ID: 2d56a1d2a83b
Revises: 3c6350ea0e
Create Date: 2015-02-10 12:53:37.205025

"""

# revision identifiers, used by Alembic.
revision = '2d56a1d2a83b'
down_revision = '3c6350ea0e'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('request', sa.Column('address', sa.String(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('request', 'address')
    ### end Alembic commands ###
