"""empty message

Revision ID: 2d64c2eb87ce
Revises: 57ac64c900ef
Create Date: 2015-10-03 03:22:02.150270

"""

# revision identifiers, used by Alembic.
revision = '2d64c2eb87ce'
down_revision = '57ac64c900ef'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user-department_assoc',
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['department.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user-department_assoc')
    ### end Alembic commands ###
