"""empty message

Revision ID: 2e3e9a7877d6
Revises: 199584d9839f
Create Date: 2015-06-19 03:14:52.299366

"""

# revision identifiers, used by Alembic.
revision = '2e3e9a7877d6'
down_revision = '199584d9839f'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('proposal', sa.Column('time_answered', sa.DateTime(), nullable=True))
    op.add_column('rating', sa.Column('is_question', sa.Boolean(), nullable=True))
    op.add_column('rating', sa.Column('is_session', sa.Boolean(), nullable=True))
    op.add_column('rating', sa.Column('is_task', sa.Boolean(), nullable=True))
    op.add_column('rating', sa.Column('time_created', sa.DateTime(), nullable=True))
    op.add_column('rating', sa.Column('time_guru_rated', sa.DateTime(), nullable=True))
    op.add_column('rating', sa.Column('time_student_rated', sa.DateTime(), nullable=True))
    op.add_column('request', sa.Column('rating_id', sa.Integer(), nullable=True))
    op.add_column('request', sa.Column('time_accepted', sa.DateTime(), nullable=True))
    op.add_column('request', sa.Column('transaction_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'request', 'transaction', ['transaction_id'], ['id'])
    op.create_foreign_key(None, 'request', 'rating', ['rating_id'], ['id'])
    op.add_column('transaction', sa.Column('is_question', sa.Boolean(), nullable=True))
    op.add_column('transaction', sa.Column('is_session', sa.Boolean(), nullable=True))
    op.add_column('transaction', sa.Column('is_task', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transaction', 'is_task')
    op.drop_column('transaction', 'is_session')
    op.drop_column('transaction', 'is_question')
    op.drop_constraint(None, 'request', type_='foreignkey')
    op.drop_constraint(None, 'request', type_='foreignkey')
    op.drop_column('request', 'transaction_id')
    op.drop_column('request', 'time_accepted')
    op.drop_column('request', 'rating_id')
    op.drop_column('rating', 'time_student_rated')
    op.drop_column('rating', 'time_guru_rated')
    op.drop_column('rating', 'time_created')
    op.drop_column('rating', 'is_task')
    op.drop_column('rating', 'is_session')
    op.drop_column('rating', 'is_question')
    op.drop_column('proposal', 'time_answered')
    ### end Alembic commands ###
