"""empty message

Revision ID: 2e436311abbd
Revises: 3f7e29c2945
Create Date: 2015-08-07 12:06:32.292415

"""

# revision identifiers, used by Alembic.
revision = '2e436311abbd'
down_revision = '3f7e29c2945'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('device', sa.Column('device_load_time', sa.Float(), nullable=True))
    op.add_column('device', sa.Column('network_speed', sa.String(), nullable=True))
    op.add_column('device', sa.Column('typical_network_speed', sa.String(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('device', 'typical_network_speed')
    op.drop_column('device', 'network_speed')
    op.drop_column('device', 'device_load_time')
    ### end Alembic commands ###
