"""empty message

Revision ID: 2e4b19b36a8c
Revises: 30a870f45ef5
Create Date: 2015-11-19 15:17:27.079365

"""

# revision identifiers, used by Alembic.
revision = '2e4b19b36a8c'
down_revision = '30a870f45ef5'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
