"""empty message

Revision ID: 2f3283e1e77c
Revises: 223d7ad7a26b
Create Date: 2015-03-30 14:04:26.421146

"""

# revision identifiers, used by Alembic.
revision = '2f3283e1e77c'
down_revision = '223d7ad7a26b'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
