"""empty message

Revision ID: 2ffe396b64ad
Revises: 1b3a71d91bdc
Create Date: 2015-06-07 00:06:30.107253

"""

# revision identifiers, used by Alembic.
revision = '2ffe396b64ad'
down_revision = '1b3a71d91bdc'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('file', sa.Column('proposal_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'file', 'proposal', ['proposal_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'file', type_='foreignkey')
    op.drop_column('file', 'proposal_id')
    ### end Alembic commands ###
