"""empty message

Revision ID: 30a870f45ef5
Revises: de9f07a5b76
Create Date: 2015-11-17 22:21:50.218361

"""

# revision identifiers, used by Alembic.
revision = '30a870f45ef5'
down_revision = 'de9f07a5b76'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('person_friendly', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'person_friendly')
    ### end Alembic commands ###
