"""empty message

Revision ID: 30f1eca0512f
Revises: 38ab6206d291
Create Date: 2015-06-19 13:16:27.262718

"""

# revision identifiers, used by Alembic.
revision = '30f1eca0512f'
down_revision = '38ab6206d291'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('request', sa.Column('university_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'request', 'university', ['university_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'request', type_='foreignkey')
    op.drop_column('request', 'university_id')
    ### end Alembic commands ###
