"""Adding response rate column

Revision ID: 3183552ed3f
Revises: 1bafbb2c8f5d
Create Date: 2014-12-02 21:47:44.831758

"""

# revision identifiers, used by Alembic.
revision = '3183552ed3f'
down_revision = '1bafbb2c8f5d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('response_rate', sa.Float(), nullable=True))

    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('response_rate')

    ### end Alembic commands ###
