"""empty message

Revision ID: 324d856a0a69
Revises: 49ec1af51c47
Create Date: 2015-12-17 00:17:20.701582

"""

# revision identifiers, used by Alembic.
revision = '324d856a0a69'
down_revision = '49ec1af51c47'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_alumni', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'is_alumni')
    ### end Alembic commands ###
