"""added request-contacted-tutors_assoc, request.is_urgent, request.time_pending_began ### removed is_expired, is_cancelled

Revision ID: 330925c9459f
Revises: 3eb48b64dd7c
Create Date: 2014-12-08 21:54:43.538423

"""

# revision identifiers, used by Alembic.
revision = '330925c9459f'
down_revision = '3eb48b64dd7c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('request-contacted-tutors_assoc',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('request_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['request_id'], ['request.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
    )
    with op.batch_alter_table(u'request', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_urgent', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('time_pending_began', sa.DateTime(), nullable=True))
        batch_op.drop_column('is_expired')
        batch_op.drop_column('is_canceled')

    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table(u'request', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_canceled', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('is_expired', sa.BOOLEAN(), server_default=sa.text(u'false'), autoincrement=False, nullable=True))
        batch_op.drop_column('time_pending_began')
        batch_op.drop_column('is_urgent')

    op.drop_table('request-contacted-tutors_assoc')
    ### end Alembic commands ###
