"""empty message

Revision ID: 336826b35462
Revises: 2d56a1d2a83b
Create Date: 2015-02-11 06:30:55.072696

"""

# revision identifiers, used by Alembic.
revision = '336826b35462'
down_revision = '2d56a1d2a83b'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('session', sa.Column('address', sa.String(), nullable=True))
    op.add_column('session', sa.Column('in_person', sa.Boolean(), nullable=True))
    op.add_column('session', sa.Column('online', sa.Boolean(), nullable=True))
    op.add_column('session', sa.Column('request_id', sa.Integer(), nullable=True))
    op.add_column('session', sa.Column('time_estimate', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'session', 'request', ['request_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'session', type_='foreignkey')
    op.drop_column('session', 'time_estimate')
    op.drop_column('session', 'request_id')
    op.drop_column('session', 'online')
    op.drop_column('session', 'in_person')
    op.drop_column('session', 'address')
    ### end Alembic commands ###
