"""empty message

Revision ID: 3497ca226fe6
Revises: 439cfcaed5e9
Create Date: 2015-10-06 12:57:14.719059

"""

# revision identifiers, used by Alembic.
revision = '3497ca226fe6'
down_revision = '439cfcaed5e9'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('university', sa.Column('courses_sanitized', sa.Boolean(), nullable=True))
    op.add_column('university', sa.Column('departments_sanitized', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('university', 'departments_sanitized')
    op.drop_column('university', 'courses_sanitized')
    ### end Alembic commands ###
