"""empty message

Revision ID: 34c38a39e44
Revises: 3bfa1d3ad49c
Create Date: 2015-03-03 03:21:56.777715

"""

# revision identifiers, used by Alembic.
revision = '34c38a39e44'
down_revision = '3bfa1d3ad49c'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('course', sa.Column('is_popular', sa.Boolean(), nullable=True))
    op.add_column('event', sa.Column('estimated_rank_after', sa.Integer(), nullable=True))
    op.add_column('event', sa.Column('official_rank_after', sa.Integer(), nullable=True))
    op.add_column('event', sa.Column('official_rank_before', sa.Integer(), nullable=True))
    op.add_column('event', sa.Column('rank_guru_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'event', 'user', ['rank_guru_id'], ['id'])
    op.add_column('university', sa.Column('emails_student_only', sa.Boolean(), nullable=True))
    op.add_column('university', sa.Column('is_public', sa.Boolean(), nullable=True))
    op.add_column('university', sa.Column('num_popular_courses', sa.Integer(), nullable=True))
    op.add_column('university', sa.Column('ready_to_launch', sa.Boolean(), nullable=True))
    op.add_column('university', sa.Column('school_casual_name', sa.String(), nullable=True))
    op.add_column('university', sa.Column('school_color_one', sa.String(), nullable=True))
    op.add_column('university', sa.Column('school_color_two', sa.String(), nullable=True))
    op.add_column('university', sa.Column('school_logo', sa.String(), nullable=True))
    op.add_column('university', sa.Column('school_mascot_name', sa.String(), nullable=True))
    op.add_column('university', sa.Column('school_population', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('estimated_guru_rank', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('estimated_guru_rank_last_updated', sa.DateTime(), nullable=True))
    op.add_column('user', sa.Column('estimated_guru_score', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('official_guru_rank', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('official_guru_rank_last_updated', sa.DateTime(), nullable=True))
    op.add_column('user', sa.Column('official_guru_score', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'official_guru_score')
    op.drop_column('user', 'official_guru_rank_last_updated')
    op.drop_column('user', 'official_guru_rank')
    op.drop_column('user', 'estimated_guru_score')
    op.drop_column('user', 'estimated_guru_rank_last_updated')
    op.drop_column('user', 'estimated_guru_rank')
    op.drop_column('university', 'school_population')
    op.drop_column('university', 'school_mascot_name')
    op.drop_column('university', 'school_logo')
    op.drop_column('university', 'school_color_two')
    op.drop_column('university', 'school_color_one')
    op.drop_column('university', 'school_casual_name')
    op.drop_column('university', 'ready_to_launch')
    op.drop_column('university', 'num_popular_courses')
    op.drop_column('university', 'is_public')
    op.drop_column('university', 'emails_student_only')
    op.drop_constraint(None, 'event', type_='foreignkey')
    op.drop_column('event', 'rank_guru_id')
    op.drop_column('event', 'official_rank_before')
    op.drop_column('event', 'official_rank_after')
    op.drop_column('event', 'estimated_rank_after')
    op.drop_column('course', 'is_popular')
    ### end Alembic commands ###
