"""empty message

Revision ID: 34d69f0f368c
Revises: 30f1eca0512f
Create Date: 2015-06-19 13:54:01.686225

"""

# revision identifiers, used by Alembic.
revision = '34d69f0f368c'
down_revision = '30f1eca0512f'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('request', sa.Column('category', sa.String(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('request', 'category')
    ### end Alembic commands ###
