"""empty message

Revision ID: 356288871f17
Revises: 1c5b3d184bf1
Create Date: 2015-03-09 21:34:07.522770

"""

# revision identifiers, used by Alembic.
revision = '356288871f17'
down_revision = '1c5b3d184bf1'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('referral_code', sa.String(), nullable=True))
    op.add_column('user', sa.Column('referred_by_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'user', 'user', ['referred_by_id'], ['id'])
    op.drop_column('user', 'referral_link')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('referral_link', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_column('user', 'referred_by_id')
    op.drop_column('user', 'referral_code')
    ### end Alembic commands ###
