"""empty message

Revision ID: 360b6db0eb6f
Revises: 13c026f49342
Create Date: 2015-11-30 17:30:05.461354

"""

# revision identifiers, used by Alembic.
revision = '360b6db0eb6f'
down_revision = '13c026f49342'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipient', sa.Column('campaign_args', sa.String(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recipient', 'campaign_args')
    ### end Alembic commands ###
