"""empty message

Revision ID: 3663cb2af20a
Revises: b597acec3a2
Create Date: 2016-02-13 23:58:46.121765

"""

# revision identifiers, used by Alembic.
revision = '3663cb2af20a'
down_revision = 'b597acec3a2'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transaction', sa.Column('credits', sa.Float(), nullable=True))
    op.add_column('transaction', sa.Column('credits_after', sa.Float(), nullable=True))
    op.add_column('transaction', sa.Column('credits_before', sa.Float(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transaction', 'credits_before')
    op.drop_column('transaction', 'credits_after')
    op.drop_column('transaction', 'credits')
    ### end Alembic commands ###
