"""empty message

Revision ID: 3690f4520381
Revises: 2f3283e1e77c
Create Date: 2015-05-03 21:55:37.988736

"""

# revision identifiers, used by Alembic.
revision = '3690f4520381'
down_revision = '2f3283e1e77c'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('estimated_rank_before', sa.Integer(), nullable=True))
    op.add_column('message', sa.Column('support_ticket_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'message', 'support', ['support_ticket_id'], ['id'])
    op.add_column('proposal', sa.Column('guru_description', sa.Float(), nullable=True))
    op.add_column('proposal', sa.Column('guru_price', sa.Float(), nullable=True))
    op.add_column('proposal', sa.Column('guru_proposed_price', sa.Float(), nullable=True))
    op.add_column('proposal', sa.Column('student_price', sa.Float(), nullable=True))
    op.add_column('request', sa.Column('contact_email', sa.Boolean(), nullable=True))
    op.add_column('request', sa.Column('contact_push', sa.Boolean(), nullable=True))
    op.add_column('request', sa.Column('contact_text', sa.Boolean(), nullable=True))
    op.add_column('support', sa.Column('assigned_admin_id', sa.Integer(), nullable=True))
    op.add_column('support', sa.Column('time_updated', sa.DateTime(), nullable=True))
    op.create_foreign_key(None, 'support', 'user', ['assigned_admin_id'], ['id'])
    op.add_column('user', sa.Column('current_hourly', sa.Float(), nullable=True))
    op.add_column('user', sa.Column('github_id', sa.String(), nullable=True))
    op.add_column('user', sa.Column('instagram_id', sa.String(), nullable=True))
    op.add_column('user', sa.Column('is_admin', sa.Boolean(), nullable=True))
    op.add_column('user', sa.Column('is_support_admin', sa.Boolean(), nullable=True))
    op.add_column('user', sa.Column('linkedin_id', sa.String(), nullable=True))
    op.add_column('user', sa.Column('outside_university', sa.Boolean(), nullable=True))
    op.add_column('user', sa.Column('spotify_id', sa.String(), nullable=True))
    op.add_column('user', sa.Column('summer_15', sa.Boolean(), nullable=True))
    op.add_column('user', sa.Column('text_notifications', sa.Boolean(), nullable=True))
    op.add_column('user', sa.Column('uber_friendly', sa.Boolean(), nullable=True))
    op.add_column('user', sa.Column('uber_id', sa.String(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'uber_id')
    op.drop_column('user', 'uber_friendly')
    op.drop_column('user', 'text_notifications')
    op.drop_column('user', 'summer_15')
    op.drop_column('user', 'spotify_id')
    op.drop_column('user', 'outside_university')
    op.drop_column('user', 'linkedin_id')
    op.drop_column('user', 'is_support_admin')
    op.drop_column('user', 'is_admin')
    op.drop_column('user', 'instagram_id')
    op.drop_column('user', 'github_id')
    op.drop_column('user', 'current_hourly')
    op.drop_constraint(None, 'support', type_='foreignkey')
    op.drop_column('support', 'time_updated')
    op.drop_column('support', 'assigned_admin_id')
    op.drop_column('request', 'contact_text')
    op.drop_column('request', 'contact_push')
    op.drop_column('request', 'contact_email')
    op.drop_column('proposal', 'student_price')
    op.drop_column('proposal', 'guru_proposed_price')
    op.drop_column('proposal', 'guru_price')
    op.drop_column('proposal', 'guru_description')
    op.drop_constraint(None, 'message', type_='foreignkey')
    op.drop_column('message', 'support_ticket_id')
    op.drop_column('event', 'estimated_rank_before')
    ### end Alembic commands ###
