"""empty message

Revision ID: 36dfa93286f
Revises: 1b8fd18b254c
Create Date: 2015-03-15 12:11:12.340998

"""

# revision identifiers, used by Alembic.
revision = '36dfa93286f'
down_revision = '1b8fd18b254c'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('device', sa.Column('background_location_enabled', sa.Boolean(), nullable=True))
    op.add_column('device', sa.Column('camera_enabled', sa.Boolean(), nullable=True))
    op.add_column('device', sa.Column('location_enabled', sa.Boolean(), nullable=True))
    op.add_column('device', sa.Column('push_notif', sa.String(), nullable=True))
    op.add_column('device', sa.Column('push_notif_enabled', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('device', 'push_notif_enabled')
    op.drop_column('device', 'push_notif')
    op.drop_column('device', 'location_enabled')
    op.drop_column('device', 'camera_enabled')
    op.drop_column('device', 'background_location_enabled')
    ### end Alembic commands ###
