"""empty message

Revision ID: 3787910089f2
Revises: 34d69f0f368c
Create Date: 2015-07-10 21:22:26.825743

"""

# revision identifiers, used by Alembic.
revision = '3787910089f2'
down_revision = '34d69f0f368c'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('course', sa.Column('variations', sa.String(), nullable=True))
    op.add_column('university', sa.Column('num_depts', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('university', 'num_depts')
    op.drop_column('course', 'variations')
    ### end Alembic commands ###
