"""empty message

Revision ID: 37ac80bcd8db
Revises: 4d2b4d33b773
Create Date: 2016-01-19 00:32:38.372669

"""

# revision identifiers, used by Alembic.
revision = '37ac80bcd8db'
down_revision = '4d2b4d33b773'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subcategory', sa.Column('unit_name', sa.String(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subcategory', 'unit_name')
    ### end Alembic commands ###
