"""empty message

Revision ID: 384d2b0b379a
Revises: 4d597f0375e3
Create Date: 2015-03-12 13:55:24.928701

"""

# revision identifiers, used by Alembic.
revision = '384d2b0b379a'
down_revision = '4d597f0375e3'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('request', sa.Column('guru_calendar_id', sa.Integer(), nullable=True))
    op.add_column('request', sa.Column('student_calendar_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'request', 'calendar', ['student_calendar_id'], ['id'])
    op.create_foreign_key(None, 'request', 'calendar', ['guru_calendar_id'], ['id'])
    op.add_column('university', sa.Column('email_attributes', sa.String(), nullable=True))
    op.add_column('university', sa.Column('public_school_ranking', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('referral_code', sa.String(), nullable=True))
    op.add_column('user', sa.Column('referred_by_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'user', 'user', ['referred_by_id'], ['id'])
    op.drop_column('user', 'referral_link')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('referral_link', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_column('user', 'referred_by_id')
    op.drop_column('user', 'referral_code')
    op.drop_column('university', 'public_school_ranking')
    op.drop_column('university', 'email_attributes')
    op.drop_constraint(None, 'request', type_='foreignkey')
    op.drop_constraint(None, 'request', type_='foreignkey')
    op.drop_column('request', 'student_calendar_id')
    op.drop_column('request', 'guru_calendar_id')
    ### end Alembic commands ###
