"""empty message

Revision ID: 38ab6206d291
Revises: 2e3e9a7877d6
Create Date: 2015-06-19 07:00:55.762247

"""

# revision identifiers, used by Alembic.
revision = '38ab6206d291'
down_revision = '2e3e9a7877d6'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transaction', sa.Column('rating_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'transaction', 'rating', ['rating_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transaction', type_='foreignkey')
    op.drop_column('transaction', 'rating_id')
    ### end Alembic commands ###
