"""empty message

Revision ID: 3a78b3025dd4
Revises: 2e4b19b36a8c
Create Date: 2015-11-19 15:18:06.429045

"""

# revision identifiers, used by Alembic.
revision = '3a78b3025dd4'
down_revision = '2e4b19b36a8c'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('major', sa.String(), nullable=True))
    op.add_column('user', sa.Column('year', sa.String(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'year')
    op.drop_column('user', 'major')
    ### end Alembic commands ###
