"""empty message

Revision ID: 3c6350ea0e
Revises: 23f9b2704276
Create Date: 2015-02-10 04:05:54.347750

"""

# revision identifiers, used by Alembic.
revision = '3c6350ea0e'
down_revision = '23f9b2704276'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('guru_discoverability', sa.Boolean(), nullable=True))
    op.add_column('user', sa.Column('guru_mode', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'guru_mode')
    op.drop_column('user', 'guru_discoverability')
    ### end Alembic commands ###
