"""empty message

Revision ID: 3c9d11304b22
Revises: 490d39fa20cb
Create Date: 2015-08-05 22:53:06.877460

"""

# revision identifiers, used by Alembic.
revision = '3c9d11304b22'
down_revision = '490d39fa20cb'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('device', sa.Column('body_load_time', sa.DateTime(), nullable=True))
    op.add_column('device', sa.Column('update_load_time', sa.Float(), nullable=True))
    op.add_column('user', sa.Column('guru_deposit', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'guru_deposit')
    op.drop_column('device', 'update_load_time')
    op.drop_column('device', 'body_load_time')
    ### end Alembic commands ###
