"""empty message

Revision ID: 3e086433172a
Revises: 54b97e8c985a
Create Date: 2016-01-11 01:13:04.384889

"""

# revision identifiers, used by Alembic.
revision = '3e086433172a'
down_revision = '54b97e8c985a'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('university', sa.Column('school_color_dark', sa.String(), nullable=True))
    op.add_column('university', sa.Column('school_color_light', sa.String(), nullable=True))
    op.add_column('university', sa.Column('school_color_primary', sa.String(), nullable=True))
    op.add_column('university', sa.Column('school_tiny_name', sa.String(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('university', 'school_tiny_name')
    op.drop_column('university', 'school_color_primary')
    op.drop_column('university', 'school_color_light')
    op.drop_column('university', 'school_color_dark')
    ### end Alembic commands ###
