"""empty message

Revision ID: 3e53fb7d5311
Revises: 536f14a2da0e
Create Date: 2015-02-06 14:49:47.264858

"""

# revision identifiers, used by Alembic.
revision = '3e53fb7d5311'
down_revision = '536f14a2da0e'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
