"""empty message

Revision ID: 3e56cd28c6e1
Revises: 2ce926c3cc69
Create Date: 2015-12-06 23:35:04.948555

"""

# revision identifiers, used by Alembic.
revision = '3e56cd28c6e1'
down_revision = '2ce926c3cc69'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('calendar_event', sa.Column('is_day_event', sa.Boolean(), nullable=True))
    op.add_column('calendar_event', sa.Column('portfolio_item_id', sa.Integer(), nullable=True))
    op.add_column('calendar_event', sa.Column('shop_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'calendar_event', 'portfolio_item', ['portfolio_item_id'], ['id'])
    op.create_foreign_key(None, 'calendar_event', 'shop', ['shop_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'calendar_event', type_='foreignkey')
    op.drop_constraint(None, 'calendar_event', type_='foreignkey')
    op.drop_column('calendar_event', 'shop_id')
    op.drop_column('calendar_event', 'portfolio_item_id')
    op.drop_column('calendar_event', 'is_day_event')
    ### end Alembic commands ###
