"""added to Request - is_canceled, time_canceled, time_expired

Revision ID: 3eb48b64dd7c
Revises: 4a3f9e090384
Create Date: 2014-12-07 21:35:25.867457

"""

# revision identifiers, used by Alembic.
revision = '3eb48b64dd7c'
down_revision = '4a3f9e090384'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('request', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_canceled', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('time_canceled', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('time_expired', sa.DateTime(), nullable=True))

    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('request', schema=None) as batch_op:
        batch_op.drop_column('time_expired')
        batch_op.drop_column('time_canceled')
        batch_op.drop_column('is_canceled')

    ### end Alembic commands ###
