"""empty message

Revision ID: 3f7e29c2945
Revises: 405cc3ab719a
Create Date: 2015-08-05 23:15:31.999636

"""

# revision identifiers, used by Alembic.
revision = '3f7e29c2945'
down_revision = '405cc3ab719a'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('device', sa.Column('body_load_time', sa.Float(), nullable=True))
    op.add_column('device', sa.Column('is_test_device', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('device', 'is_test_device')
    op.drop_column('device', 'body_load_time')
    ### end Alembic commands ###
