"""empty message

Revision ID: 405cc3ab719a
Revises: 3c9d11304b22
Create Date: 2015-08-05 23:15:14.286599

"""

# revision identifiers, used by Alembic.
revision = '405cc3ab719a'
down_revision = '3c9d11304b22'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('device', 'body_load_time')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('device', sa.Column('body_load_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    ### end Alembic commands ###
