"""empty message

Revision ID: 40afa070f60e
Revises: 42b40476dd54
Create Date: 2015-12-28 00:18:36.320696

"""

# revision identifiers, used by Alembic.
revision = '40afa070f60e'
down_revision = '42b40476dd54'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('request', sa.Column('payment_card_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'request', 'card', ['payment_card_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'request', type_='foreignkey')
    op.drop_column('request', 'payment_card_id')
    ### end Alembic commands ###
