"""empty message

Revision ID: 40ca3b153da3
Revises: 4dea761ea2d3
Create Date: 2015-01-23 02:35:45.950543

"""

# revision identifiers, used by Alembic.
revision = '40ca3b153da3'
down_revision = '4dea761ea2d3'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('campaign', sa.Column('time_created', sa.DateTime(), nullable=True))
    op.add_column('campaign', sa.Column('time_scheduled', sa.DateTime(), nullable=True))
    op.drop_column('campaign', 'time_uploaded')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('campaign', sa.Column('time_uploaded', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('campaign', 'time_scheduled')
    op.drop_column('campaign', 'time_created')
    ### end Alembic commands ###
