"""empty message

Revision ID: 4101ccf4ac2b
Revises: 3787910089f2
Create Date: 2015-07-10 21:38:13.422229

"""

# revision identifiers, used by Alembic.
revision = '4101ccf4ac2b'
down_revision = '3787910089f2'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('course', sa.Column('department_id', sa.Integer(), nullable=True))
    op.add_column('course', sa.Column('rmp_only', sa.Boolean(), nullable=True))
    op.add_column('course', sa.Column('source', sa.String(), nullable=True))
    op.add_column('course', sa.Column('times_mentioned', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'course', 'department', ['department_id'], ['id'])
    op.add_column('department', sa.Column('abbr', sa.String(), nullable=True))
    op.add_column('department', sa.Column('is_popular', sa.Boolean(), nullable=True))
    op.add_column('department', sa.Column('name', sa.String(), nullable=True))
    op.add_column('department', sa.Column('num_courses', sa.Integer(), nullable=True))
    op.add_column('department', sa.Column('num_popular_courses', sa.Integer(), nullable=True))
    op.add_column('department', sa.Column('short_name', sa.String(), nullable=True))
    op.add_column('department', sa.Column('source', sa.String(), nullable=True))
    op.add_column('department', sa.Column('time_created', sa.DateTime(), nullable=True))
    op.add_column('department', sa.Column('time_updated', sa.DateTime(), nullable=True))
    op.add_column('department', sa.Column('times_mentioned', sa.Integer(), nullable=True))
    op.add_column('department', sa.Column('variations', sa.String(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('department', 'variations')
    op.drop_column('department', 'times_mentioned')
    op.drop_column('department', 'time_updated')
    op.drop_column('department', 'time_created')
    op.drop_column('department', 'source')
    op.drop_column('department', 'short_name')
    op.drop_column('department', 'num_popular_courses')
    op.drop_column('department', 'num_courses')
    op.drop_column('department', 'name')
    op.drop_column('department', 'is_popular')
    op.drop_column('department', 'abbr')
    op.drop_constraint(None, 'course', type_='foreignkey')
    op.drop_column('course', 'times_mentioned')
    op.drop_column('course', 'source')
    op.drop_column('course', 'rmp_only')
    op.drop_column('course', 'department_id')
    ### end Alembic commands ###
