"""add fb_id column

Revision ID: 41c02efd8a7d
Revises: 43e13caa475b
Create Date: 2014-12-05 19:07:22.910646

"""

# revision identifiers, used by Alembic.
revision = '41c02efd8a7d'
down_revision = '43e13caa475b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fb_id', sa.String(length=64), nullable=True))

    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('fb_id')

    ### end Alembic commands ###
