"""empty message

Revision ID: 42b40476dd54
Revises: 177bdb33eb5f
Create Date: 2015-12-27 22:03:37.913281

"""

# revision identifiers, used by Alembic.
revision = '42b40476dd54'
down_revision = '177bdb33eb5f'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(u'file_message_id_fkey', 'file', type_='foreignkey')
    op.drop_column('file', 'message_id')
    op.add_column('message', sa.Column('file_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'message', 'file', ['file_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'message', type_='foreignkey')
    op.drop_column('message', 'file_id')
    op.add_column('file', sa.Column('message_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(u'file_message_id_fkey', 'file', 'message', ['message_id'], ['id'])
    ### end Alembic commands ###
