"""empty message

Revision ID: 42cda23fbc7d
Revises: 1bdb7d2eff90
Create Date: 2016-03-01 14:59:58.196215

"""

# revision identifiers, used by Alembic.
revision = '42cda23fbc7d'
down_revision = '1bdb7d2eff90'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_hs_parent', sa.Boolean(), nullable=True))
    op.add_column('user', sa.Column('is_parent', sa.Boolean(), nullable=True))
    op.add_column('user', sa.Column('is_professional', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'is_professional')
    op.drop_column('user', 'is_parent')
    op.drop_column('user', 'is_hs_parent')
    ### end Alembic commands ###
