"""empty message

Revision ID: 439cfcaed5e9
Revises: 1e9256b4a00b
Create Date: 2015-10-06 12:24:02.499235

"""

# revision identifiers, used by Alembic.
revision = '439cfcaed5e9'
down_revision = '1e9256b4a00b'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
