"""added columns to payment

Revision ID: 43e13caa475b
Revises: 515853c23e1c
Create Date: 2014-12-04 14:53:41.924422

"""

# revision identifiers, used by Alembic.
revision = '43e13caa475b'
down_revision = '515853c23e1c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payment', sa.Column('num_hours', sa.Integer(), nullable=True))
    op.add_column('payment', sa.Column('num_minutes', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payment', 'num_minutes')
    op.drop_column('payment', 'num_hours')
    ### end Alembic commands ###
