"""empty message

Revision ID: 46be1e03f8d4
Revises: 2ea080f4256e
Create Date: 2015-10-04 18:57:19.086492

"""

# revision identifiers, used by Alembic.
revision = '46be1e03f8d4'
down_revision = '2ea080f4256e'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('category', sa.Column('background_url', sa.String(), nullable=True))
    op.add_column('category', sa.Column('description', sa.String(), nullable=True))
    op.add_column('category', sa.Column('icon_url', sa.String(), nullable=True))
    op.add_column('category', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.add_column('category', sa.Column('is_approved', sa.Boolean(), nullable=True))
    op.add_column('subcategory', sa.Column('description', sa.String(), nullable=True))
    op.add_column('subcategory', sa.Column('icon_url', sa.String(), nullable=True))
    op.add_column('subcategory', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.add_column('subcategory', sa.Column('is_approved', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subcategory', 'is_approved')
    op.drop_column('subcategory', 'is_active')
    op.drop_column('subcategory', 'icon_url')
    op.drop_column('subcategory', 'description')
    op.drop_column('category', 'is_approved')
    op.drop_column('category', 'is_active')
    op.drop_column('category', 'icon_url')
    op.drop_column('category', 'description')
    op.drop_column('category', 'background_url')
    ### end Alembic commands ###
