"""empty message

Revision ID: 4867cbf98dce
Revises: 57dd20fa9c66
Create Date: 2015-02-28 05:29:35.953359

"""

# revision identifiers, used by Alembic.
revision = '4867cbf98dce'
down_revision = '57dd20fa9c66'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('card', sa.Column('is_transfer_card', sa.Boolean(), nullable=True))
    op.drop_column('card', 'is_cashout_card')
    op.add_column('user', sa.Column('total_cashed_out', sa.Float(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'total_cashed_out')
    op.add_column('card', sa.Column('is_cashout_card', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('card', 'is_transfer_card')
    ### end Alembic commands ###
