"""empty message

Revision ID: 487e4d824be1
Revises: 3e56cd28c6e1
Create Date: 2015-12-07 12:46:08.166160

"""

# revision identifiers, used by Alembic.
revision = '487e4d824be1'
down_revision = '3e56cd28c6e1'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rating', sa.Column('course_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'rating', 'course', ['course_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'rating', type_='foreignkey')
    op.drop_column('rating', 'course_id')
    ### end Alembic commands ###
