"""empty message

Revision ID: 48ade5c27bcf
Revises: 2be24328f877
Create Date: 2015-02-16 16:25:40.358845

"""

# revision identifiers, used by Alembic.
revision = '48ade5c27bcf'
down_revision = '2be24328f877'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
