"""empty message

Revision ID: 490d39fa20cb
Revises: 61fef1dd062
Create Date: 2015-07-28 09:06:24.107364

"""

# revision identifiers, used by Alembic.
revision = '490d39fa20cb'
down_revision = '61fef1dd062'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('debit_card_confirmed', sa.Boolean(), nullable=True))
    op.add_column('user', sa.Column('phone_number_token', sa.String(), nullable=True))
    op.add_column('user', sa.Column('school_email', sa.String(), nullable=True))
    op.add_column('user', sa.Column('school_email_confirmed', sa.Boolean(), nullable=True))
    op.add_column('user', sa.Column('school_email_token', sa.String(), nullable=True))
    op.add_column('user', sa.Column('transcript_verified_by_admin', sa.Boolean(), nullable=True))
    op.add_column('user', sa.Column('tutoring_platforms_description', sa.String(), nullable=True))
    op.add_column('user', sa.Column('tutoring_platforms_verified_by_admin', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'tutoring_platforms_verified_by_admin')
    op.drop_column('user', 'tutoring_platforms_description')
    op.drop_column('user', 'transcript_verified_by_admin')
    op.drop_column('user', 'school_email_token')
    op.drop_column('user', 'school_email_confirmed')
    op.drop_column('user', 'school_email')
    op.drop_column('user', 'phone_number_token')
    op.drop_column('user', 'debit_card_confirmed')
    ### end Alembic commands ###
