"""empty message

Revision ID: 49803135cec4
Revises: 36dfa93286f
Create Date: 2015-03-15 19:37:46.314903

"""

# revision identifiers, used by Alembic.
revision = '49803135cec4'
down_revision = '36dfa93286f'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('device', sa.Column('is_current', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('device', 'is_current')
    ### end Alembic commands ###
