"""empty message

Revision ID: 49ec1af51c47
Revises: 20a84935876e
Create Date: 2015-12-16 23:55:56.482347

"""

# revision identifiers, used by Alembic.
revision = '49ec1af51c47'
down_revision = '20a84935876e'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('portfolio_item', sa.Column('activated', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('portfolio_item', 'activated')
    ### end Alembic commands ###
