"""empty message

Revision ID: 4a87f55f4651
Revises: 360b6db0eb6f
Create Date: 2015-12-03 16:22:38.183117

"""

# revision identifiers, used by Alembic.
revision = '4a87f55f4651'
down_revision = '360b6db0eb6f'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('currency',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('icon_url', sa.String(), nullable=True),
    sa.Column('is_approved', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user-currency.id',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('currency_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['currency_id'], ['currency.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
    )
    op.create_table('shop',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('guru_id', sa.Integer(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('dark_mode', sa.Boolean(), nullable=True),
    sa.Column('light_mode', sa.Boolean(), nullable=True),
    sa.Column('banner_url', sa.String(), nullable=True),
    sa.Column('is_featured', sa.Boolean(), nullable=True),
    sa.Column('avg_rating', sa.Float(), nullable=True),
    sa.Column('public_url', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ),
    sa.ForeignKeyConstraint(['guru_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column(u'portfolio_item', sa.Column('shop_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'portfolio_item', 'shop', ['shop_id'], ['id'])
    op.add_column(u'resource', sa.Column('icon_url', sa.String(), nullable=True))
    op.add_column(u'resource', sa.Column('is_featured', sa.Boolean(), nullable=True))
    op.add_column(u'resource', sa.Column('is_file', sa.Boolean(), nullable=True))
    op.add_column(u'resource', sa.Column('is_profile', sa.Boolean(), nullable=True))
    op.add_column(u'resource', sa.Column('is_tutoring_profile', sa.Boolean(), nullable=True))
    op.add_column(u'resource', sa.Column('is_url', sa.Boolean(), nullable=True))
    op.add_column(u'resource', sa.Column('root_domain_url', sa.String(), nullable=True))
    op.add_column(u'resource', sa.Column('site_url', sa.String(), nullable=True))
    op.add_column(u'tag', sa.Column('is_ingredient', sa.Boolean(), nullable=True))
    op.add_column(u'tag', sa.Column('is_sale_item', sa.Boolean(), nullable=True))
    op.add_column(u'tag', sa.Column('portfolio_item_id', sa.Integer(), nullable=True))
    op.add_column(u'tag', sa.Column('price', sa.Float(), nullable=True))
    op.create_foreign_key(None, 'tag', 'portfolio_item', ['portfolio_item_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tag', type_='foreignkey')
    op.drop_column(u'tag', 'price')
    op.drop_column(u'tag', 'portfolio_item_id')
    op.drop_column(u'tag', 'is_sale_item')
    op.drop_column(u'tag', 'is_ingredient')
    op.drop_column(u'resource', 'site_url')
    op.drop_column(u'resource', 'root_domain_url')
    op.drop_column(u'resource', 'is_url')
    op.drop_column(u'resource', 'is_tutoring_profile')
    op.drop_column(u'resource', 'is_profile')
    op.drop_column(u'resource', 'is_file')
    op.drop_column(u'resource', 'is_featured')
    op.drop_column(u'resource', 'icon_url')
    op.drop_constraint(None, 'portfolio_item', type_='foreignkey')
    op.drop_column(u'portfolio_item', 'shop_id')
    op.drop_table('shop')
    op.drop_table('user-currency.id')
    op.drop_table('currency')
    ### end Alembic commands ###
