"""empty message

Revision ID: 4a8aaa47889d
Revises: 1e2d5de564e4
Create Date: 2015-02-08 23:22:09.876765

"""

# revision identifiers, used by Alembic.
revision = '4a8aaa47889d'
down_revision = '1e2d5de564e4'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transaction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('_type', sa.Integer(), nullable=True),
    sa.Column('time_created', sa.DateTime(), nullable=True),
    sa.Column('time_processed', sa.DateTime(), nullable=True),
    sa.Column('time_disputed', sa.DateTime(), nullable=True),
    sa.Column('time_refunded', sa.DateTime(), nullable=True),
    sa.Column('deactivated', sa.Boolean(), nullable=True),
    sa.Column('student_amount', sa.Float(), nullable=True),
    sa.Column('guru_amount', sa.Float(), nullable=True),
    sa.Column('stripe_amount', sa.Float(), nullable=True),
    sa.Column('profit', sa.Float(), nullable=True),
    sa.Column('guru_id', sa.Integer(), nullable=True),
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.Column('card_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['card_id'], ['card.id'], ),
    sa.ForeignKeyConstraint(['guru_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column(u'event', sa.Column('status', sa.Integer(), nullable=True))
    op.add_column(u'request', sa.Column('in_person', sa.Boolean(), nullable=True))
    op.add_column(u'request', sa.Column('online', sa.Boolean(), nullable=True))
    op.add_column(u'request', sa.Column('time_estimate', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column(u'request', 'time_estimate')
    op.drop_column(u'request', 'online')
    op.drop_column(u'request', 'in_person')
    op.drop_column(u'event', 'status')
    op.drop_table('transaction')
    ### end Alembic commands ###
