"""empty message

Revision ID: 4d2b4d33b773
Revises: 3e086433172a
Create Date: 2016-01-14 18:13:28.452356

"""

# revision identifiers, used by Alembic.
revision = '4d2b4d33b773'
down_revision = '3e086433172a'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subcategory', sa.Column('avg_hourly', sa.Integer(), nullable=True))
    op.add_column('subcategory', sa.Column('avg_hourly_higher', sa.Integer(), nullable=True))
    op.add_column('subcategory', sa.Column('avg_hourly_lower', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subcategory', 'avg_hourly_lower')
    op.drop_column('subcategory', 'avg_hourly_higher')
    op.drop_column('subcategory', 'avg_hourly')
    ### end Alembic commands ###
