"""empty message

Revision ID: 4d597f0375e3
Revises: 12f90e9b151a
Create Date: 2015-03-11 11:52:45.220179

"""

# revision identifiers, used by Alembic.
revision = '4d597f0375e3'
down_revision = '12f90e9b151a'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('calendar_event', sa.Column('is_guru', sa.Boolean(), nullable=True))
    op.add_column('calendar_event', sa.Column('is_mutual', sa.Boolean(), nullable=True))
    op.add_column('calendar_event', sa.Column('is_student', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('calendar_event', 'is_student')
    op.drop_column('calendar_event', 'is_mutual')
    op.drop_column('calendar_event', 'is_guru')
    ### end Alembic commands ###
