"""empty message

Revision ID: 4dea761ea2d3
Revises: 53469aec7275
Create Date: 2015-01-23 02:32:26.230363

"""

# revision identifiers, used by Alembic.
revision = '4dea761ea2d3'
down_revision = '53469aec7275'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipient', sa.Column('university_id', sa.Integer(), nullable=True))
    op.drop_constraint(u'recipient_batch_id_fkey', 'recipient', type_='foreignkey')
    op.create_foreign_key(None, 'recipient', 'university', ['university_id'], ['id'])
    op.drop_column('recipient', 'batch_id')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipient', sa.Column('batch_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'recipient', type_='foreignkey')
    op.create_foreign_key(u'recipient_batch_id_fkey', 'recipient', 'batch', ['batch_id'], ['id'])
    op.drop_column('recipient', 'university_id')
    ### end Alembic commands ###
