"""empty message

Revision ID: 4e7f60fde00e
Revises: 25ec6f74b7f1
Create Date: 2015-11-26 22:47:49.241355

"""

# revision identifiers, used by Alembic.
revision = '4e7f60fde00e'
down_revision = '25ec6f74b7f1'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('profile_code', sa.String(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'profile_code')
    ### end Alembic commands ###
