"""empty message

Revision ID: 501b4ed64e4a
Revises: 324d856a0a69
Create Date: 2015-12-22 12:08:00.574305

"""

# revision identifiers, used by Alembic.
revision = '501b4ed64e4a'
down_revision = '324d856a0a69'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('university', sa.Column('sp16_deadline', sa.DateTime(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('university', 'sp16_deadline')
    ### end Alembic commands ###
