"""empty message

Revision ID: 519693f4b867
Revises: 554168eb78f
Create Date: 2015-02-23 20:52:20.453531

"""

# revision identifiers, used by Alembic.
revision = '519693f4b867'
down_revision = '554168eb78f'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('card', sa.Column('stripe_token', sa.String(), nullable=True))
    op.add_column('session', sa.Column('time_completed', sa.DateTime(), nullable=True))
    op.add_column('session', sa.Column('transaction_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'session', 'transaction', ['transaction_id'], ['id'])
    op.add_column('transaction', sa.Column('charge_id', sa.String(), nullable=True))
    op.add_column('transaction', sa.Column('stripe_error_string', sa.String(), nullable=True))
    op.add_column('transaction', sa.Column('transfer_id', sa.String(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transaction', 'transfer_id')
    op.drop_column('transaction', 'stripe_error_string')
    op.drop_column('transaction', 'charge_id')
    op.drop_constraint(None, 'session', type_='foreignkey')
    op.drop_column('session', 'transaction_id')
    op.drop_column('session', 'time_completed')
    op.drop_column('card', 'stripe_token')
    ### end Alembic commands ###
