"""remove estimated_hourly column from requests table

Revision ID: 51cff19af108
Revises: 3183552ed3f
Create Date: 2014-12-03 20:12:11.664898

"""

# revision identifiers, used by Alembic.
revision = '51cff19af108'
down_revision = '3183552ed3f'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('request', schema=None) as batch_op:
        batch_op.drop_column('estimated_hourly')

    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('request', schema=None) as batch_op:
        batch_op.add_column(sa.Column('estimated_hourly', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))

    ### end Alembic commands ###
