"""empty message

Revision ID: 5278c6e6db9c
Revises: de02bd37b99
Create Date: 2015-02-16 11:42:35.823921

"""

# revision identifiers, used by Alembic.
revision = '5278c6e6db9c'
down_revision = 'de02bd37b99'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('build',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message', sa.String(), nullable=True),
    sa.Column('is_major', sa.Boolean(), nullable=True),
    sa.Column('is_minor', sa.Boolean(), nullable=True),
    sa.Column('android_supported', sa.Boolean(), nullable=True),
    sa.Column('ios_supported', sa.Boolean(), nullable=True),
    sa.Column('_type', sa.Integer(), nullable=True),
    sa.Column('version_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['version_id'], ['version.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('build')
    ### end Alembic commands ###
