"""empty message

Revision ID: 53469aec7275
Revises: facc3155785
Create Date: 2015-01-21 09:56:05.515269

"""

# revision identifiers, used by Alembic.
revision = '53469aec7275'
down_revision = 'facc3155785'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('version',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('android', sa.Float(), nullable=True),
    sa.Column('ios', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('version')
    ### end Alembic commands ###
