"""empty message

Revision ID: 54b97e8c985a
Revises: 5a81f16a1754
Create Date: 2016-01-11 00:34:51.115498

"""

# revision identifiers, used by Alembic.
revision = '54b97e8c985a'
down_revision = '5a81f16a1754'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
