"""empty message

Revision ID: 554168eb78f
Revises: 1e7cb67df458
Create Date: 2015-02-22 20:55:53.682633

"""

# revision identifiers, used by Alembic.
revision = '554168eb78f'
down_revision = '1e7cb67df458'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('session', sa.Column('card_id', sa.Integer(), nullable=True))
    op.add_column('session', sa.Column('hours', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'session', 'card', ['card_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'session', type_='foreignkey')
    op.drop_column('session', 'hours')
    op.drop_column('session', 'card_id')
    ### end Alembic commands ###
