"""empty message

Revision ID: 57097843ae9d
Revises: 40c665a925a1
Create Date: 2015-03-12 11:29:29.044871

"""

# revision identifiers, used by Alembic.
revision = '57097843ae9d'
down_revision = '40c665a925a1'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(u'calendar_request_id_fkey', 'calendar', type_='foreignkey')
    op.drop_constraint(u'calendar_proposal_id_fkey', 'calendar', type_='foreignkey')
    op.drop_column('calendar', 'proposal_id')
    op.drop_column('calendar', 'request_id')
    op.add_column('request', sa.Column('guru_calendar_id', sa.Integer(), nullable=True))
    op.add_column('request', sa.Column('student_calendar_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'request', 'calendar', ['student_calendar_id'], ['id'])
    op.create_foreign_key(None, 'request', 'calendar', ['guru_calendar_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'request', type_='foreignkey')
    op.drop_constraint(None, 'request', type_='foreignkey')
    op.drop_column('request', 'student_calendar_id')
    op.drop_column('request', 'guru_calendar_id')
    op.add_column('calendar', sa.Column('request_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('calendar', sa.Column('proposal_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(u'calendar_proposal_id_fkey', 'calendar', 'proposal', ['proposal_id'], ['id'])
    op.create_foreign_key(u'calendar_request_id_fkey', 'calendar', 'request', ['request_id'], ['id'])
    ### end Alembic commands ###
