"""empty message

Revision ID: 57ac64c900ef
Revises: 60bc5f4f564
Create Date: 2015-08-12 23:26:14.140311

"""

# revision identifiers, used by Alembic.
revision = '57ac64c900ef'
down_revision = '60bc5f4f564'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('university', sa.Column('banner_url', sa.String(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('university', 'banner_url')
    ### end Alembic commands ###
