"""empty message

Revision ID: 57dd20fa9c66
Revises: 594bea69b817
Create Date: 2015-02-28 05:03:20.911742

"""

# revision identifiers, used by Alembic.
revision = '57dd20fa9c66'
down_revision = '594bea69b817'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('card', sa.Column('is_default_payment', sa.Boolean(), nullable=True))
    op.add_column('card', sa.Column('is_default_transfer', sa.Boolean(), nullable=True))
    op.drop_column('card', 'is_default')
    op.add_column('user', sa.Column('balance', sa.Float(), nullable=True))
    op.add_column('user', sa.Column('credits', sa.Float(), nullable=True))
    op.add_column('user', sa.Column('total_earned', sa.Float(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'total_earned')
    op.drop_column('user', 'credits')
    op.drop_column('user', 'balance')
    op.add_column('card', sa.Column('is_default', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('card', 'is_default_transfer')
    op.drop_column('card', 'is_default_payment')
    ### end Alembic commands ###
