"""empty message

Revision ID: 59075ca6c0ef
Revises: 40ca3b153da3
Create Date: 2015-01-23 02:38:21.074073

"""

# revision identifiers, used by Alembic.
revision = '59075ca6c0ef'
down_revision = '40ca3b153da3'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user-campaign_assoc',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('campaign_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaign.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user-campaign_assoc')
    ### end Alembic commands ###
