"""empty message

Revision ID: 594bea69b817
Revises: 519693f4b867
Create Date: 2015-02-24 20:45:17.981606

"""

# revision identifiers, used by Alembic.
revision = '594bea69b817'
down_revision = '519693f4b867'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('request', sa.Column('guru_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'request', 'user', ['guru_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'request', type_='foreignkey')
    op.drop_column('request', 'guru_id')
    ### end Alembic commands ###
