"""empty message

Revision ID: 59c982a7d8c9
Revises: f68c8331c4b
Create Date: 2015-11-21 23:01:55.924987

"""

# revision identifiers, used by Alembic.
revision = '59c982a7d8c9'
down_revision = 'f68c8331c4b'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('card', sa.Column('country', sa.String(), nullable=True))
    op.add_column('card', sa.Column('customer_email', sa.String(), nullable=True))
    op.add_column('card', sa.Column('exp_month', sa.Integer(), nullable=True))
    op.add_column('card', sa.Column('exp_year', sa.Integer(), nullable=True))
    op.add_column('card', sa.Column('funding', sa.String(), nullable=True))
    op.add_column('card', sa.Column('stripe_card_id', sa.String(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('card', 'stripe_card_id')
    op.drop_column('card', 'funding')
    op.drop_column('card', 'exp_year')
    op.drop_column('card', 'exp_month')
    op.drop_column('card', 'customer_email')
    op.drop_column('card', 'country')
    ### end Alembic commands ###
