"""empty message

Revision ID: 5a81f16a1754
Revises: 40afa070f60e
Create Date: 2016-01-06 00:42:04.774549

"""

# revision identifiers, used by Alembic.
revision = '5a81f16a1754'
down_revision = '40afa070f60e'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('university', sa.Column('sp16_start', sa.DateTime(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('university', 'sp16_start')
    ### end Alembic commands ###
