"""empty message

Revision ID: 60bc5f4f564
Revises: 28fcd465f4b3
Create Date: 2015-08-09 22:49:19.500442

"""

# revision identifiers, used by Alembic.
revision = '60bc5f4f564'
down_revision = '28fcd465f4b3'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('university', sa.Column('is_targetted', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('university', 'is_targetted')
    ### end Alembic commands ###
