"""empty message

Revision ID: 61fef1dd062
Revises: 1d605fb4d939
Create Date: 2015-07-25 12:50:22.400037

"""

# revision identifiers, used by Alembic.
revision = '61fef1dd062'
down_revision = '1d605fb4d939'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('experience', sa.Column('contributed_user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'experience', 'user', ['contributed_user_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'experience', type_='foreignkey')
    op.drop_column('experience', 'contributed_user_id')
    ### end Alembic commands ###
