"""empty message

Revision ID: 689ec249aa7
Revises: 49803135cec4
Create Date: 2015-03-20 22:23:30.862994

"""

# revision identifiers, used by Alembic.
revision = '689ec249aa7'
down_revision = '49803135cec4'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('time_open', sa.DateTime(), nullable=True),
    sa.Column('time_clicked', sa.DateTime(), nullable=True),
    sa.Column('time_visited', sa.DateTime(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('signed_up', sa.Boolean(), nullable=True),
    sa.Column('num_clicks', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###

    op.drop_table('email_user')
    ### end Alembic commands ###
