"""empty message

Revision ID: 689ec249aa7
Revises: 49803135cec4
Create Date: 2015-03-20 22:23:30.862994

"""

# revision identifiers, used by Alembic.
revision = '689ec249aa7'
down_revision = '49803135cec4'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('time_open', sa.DateTime(), nullable=True),
    sa.Column('time_clicked', sa.DateTime(), nullable=True),
    sa.Column('time_visited', sa.DateTime(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('signed_up', sa.Boolean(), nullable=True),
    sa.Column('num_clicks', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('c_name')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('c_name',
    sa.Column('table_catalog', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('table_schema', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('table_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('column_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('ordinal_position', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('column_default', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('is_nullable', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('data_type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('character_maximum_length', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('character_octet_length', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('numeric_precision', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('numeric_precision_radix', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('numeric_scale', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('datetime_precision', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('interval_type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('interval_precision', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('character_set_catalog', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('character_set_schema', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('character_set_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('collation_catalog', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('collation_schema', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('collation_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('domain_catalog', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('domain_schema', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('domain_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('udt_catalog', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('udt_schema', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('udt_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('scope_catalog', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('scope_schema', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('scope_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('maximum_cardinality', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('dtd_identifier', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('is_self_referencing', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('is_identity', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('identity_generation', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('identity_start', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('identity_increment', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('identity_maximum', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('identity_minimum', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('identity_cycle', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('is_generated', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('generation_expression', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('is_updatable', sa.VARCHAR(), autoincrement=False, nullable=True)
    )
    op.drop_table('email_user')
    ### end Alembic commands ###
