"""empty message

Revision ID: 7583748da7e
Revises: 2ffe396b64ad
Create Date: 2015-06-07 05:59:20.049408

"""

# revision identifiers, used by Alembic.
revision = '7583748da7e'
down_revision = '2ffe396b64ad'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
