"""empty message

Revision ID: a95db0310b0
Revises: 3e53fb7d5311
Create Date: 2015-02-07 23:30:00.564657

"""

# revision identifiers, used by Alembic.
revision = 'a95db0310b0'
down_revision = '3e53fb7d5311'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('position', sa.Column('longitude', sa.Float(), nullable=True))
    op.add_column('user', sa.Column('auth_token', sa.String(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'auth_token')
    op.drop_column('position', 'longitude')
    ### end Alembic commands ###
