"""empty message

Revision ID: b597acec3a2
Revises: 4be5ec8b9c68
Create Date: 2016-02-09 21:44:20.713612

"""

# revision identifiers, used by Alembic.
revision = 'b597acec3a2'
down_revision = '4be5ec8b9c68'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('position', sa.Column('address', sa.String(), nullable=True))
    op.add_column('request', sa.Column('category_id', sa.Integer(), nullable=True))
    op.add_column('request', sa.Column('subcategory_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'request', 'category', ['category_id'], ['id'])
    op.create_foreign_key(None, 'request', 'subcategory', ['subcategory_id'], ['id'])
    op.drop_column('request', 'category')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('request', sa.Column('category', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'request', type_='foreignkey')
    op.drop_constraint(None, 'request', type_='foreignkey')
    op.drop_column('request', 'subcategory_id')
    op.drop_column('request', 'category_id')
    op.drop_column('position', 'address')
    ### end Alembic commands ###
