"""empty message

Revision ID: b6a9b1d89e5
Revises: 500eb06950e
Create Date: 2015-05-26 00:07:46.938396

"""

# revision identifiers, used by Alembic.
revision = 'b6a9b1d89e5'
down_revision = '500eb06950e'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('request', sa.Column('inital_status', sa.String(), nullable=True))
    op.add_column('request', sa.Column('task_title', sa.String(), nullable=True))
    op.add_column('request', sa.Column('verb_image', sa.String(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('request', 'verb_image')
    op.drop_column('request', 'task_title')
    op.drop_column('request', 'inital_status')
    ### end Alembic commands ###
