"""empty message

Revision ID: d9e1564e623
Revises: 4a87f55f4651
Create Date: 2015-12-04 04:41:44.391825

"""

# revision identifiers, used by Alembic.
revision = 'd9e1564e623'
down_revision = '4a87f55f4651'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('course', sa.Column('num_gurus', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('guru_profile_color', sa.String(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'guru_profile_color')
    op.drop_column('course', 'num_gurus')
    ### end Alembic commands ###
