"""empty message

Revision ID: de02bd37b99
Revises: 336826b35462
Create Date: 2015-02-15 00:14:25.789553

"""

# revision identifiers, used by Alembic.
revision = 'de02bd37b99'
down_revision = '336826b35462'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipient', sa.Column('affiliations', sa.String(), nullable=True))
    op.add_column('recipient', sa.Column('major', sa.String(), nullable=True))
    op.add_column('recipient', sa.Column('name', sa.String(), nullable=True))
    op.add_column('recipient', sa.Column('title', sa.String(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recipient', 'title')
    op.drop_column('recipient', 'name')
    op.drop_column('recipient', 'major')
    op.drop_column('recipient', 'affiliations')
    ### end Alembic commands ###
