"""empty message

Revision ID: de9f07a5b76
Revises: 11d4e8179a64
Create Date: 2015-11-17 02:18:19.132693

"""

# revision identifiers, used by Alembic.
revision = 'de9f07a5b76'
down_revision = '11d4e8179a64'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('university', sa.Column('svg_url', sa.String(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('university', 'svg_url')
    ### end Alembic commands ###
