"""empty message

Revision ID: e6a107bf6f6
Revises: 5ad2a6cf2f02
Create Date: 2015-06-14 23:58:27.728192

"""

# revision identifiers, used by Alembic.
revision = 'e6a107bf6f6'
down_revision = '5ad2a6cf2f02'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('skill', sa.Column('category', sa.String(), nullable=True))
    op.add_column('skill', sa.Column('is_popular', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('skill', 'is_popular')
    op.drop_column('skill', 'category')
    ### end Alembic commands ###
