"""empty message

Revision ID: ea21455ab33
Revises: 4a8aaa47889d
Create Date: 2015-02-09 19:13:28.178205

"""

# revision identifiers, used by Alembic.
revision = 'ea21455ab33'
down_revision = '4a8aaa47889d'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
