"""empty message

Revision ID: f68c8331c4b
Revises: 3a78b3025dd4
Create Date: 2015-11-21 15:16:04.997122

"""

# revision identifiers, used by Alembic.
revision = 'f68c8331c4b'
down_revision = '3a78b3025dd4'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_activated', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'is_activated')
    ### end Alembic commands ###
