"""empty message

Revision ID: facc3155785
Revises: 
Create Date: 2015-01-21 09:55:26.794100

"""

# revision identifiers, used by Alembic.
revision = 'facc3155785'
down_revision = None
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
